//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagge.Seti.BusinessEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bagge.Seti.BusinessEntities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no posee permisos para ejecutar la acción que desea realizar.
        /// </summary>
        internal static string MethodAccessDeniedErrorMessage {
            get {
                return ResourceManager.GetString("MethodAccessDeniedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro especificado no existe.
        /// </summary>
        internal static string ObjectNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ObjectNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo CUIT debe tener el formato 00-000000000-0.
        /// </summary>
        internal static string Validators_Customer_CUIT {
            get {
                return ResourceManager.GetString("Validators.Customer.CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d{2}-\d{9}-\d{1}.
        /// </summary>
        internal static string Validators_Customer_CUIT_Pattern {
            get {
                return ResourceManager.GetString("Validators.Customer.CUIT.Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener una longitud entre 1 y 50 caracteres.
        /// </summary>
        internal static string Validators_PrimaryKeyDomainObject_Name_Length {
            get {
                return ResourceManager.GetString("Validators.PrimaryKeyDomainObject.Name.Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido.
        /// </summary>
        internal static string Validators_PrimaryKeyDomainObject_Name_Required {
            get {
                return ResourceManager.GetString("Validators.PrimaryKeyDomainObject.Name.Required", resourceCulture);
            }
        }
    }
}
