//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagge.Seti.BusinessEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bagge.Seti.BusinessEntities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene.
        /// </summary>
        internal static string Constraint_Contains {
            get {
                return ResourceManager.GetString("Constraint_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Igual a.
        /// </summary>
        internal static string Constraint_Equal {
            get {
                return ResourceManager.GetString("Constraint_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor que.
        /// </summary>
        internal static string Constraint_GreaterThan {
            get {
                return ResourceManager.GetString("Constraint_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor que.
        /// </summary>
        internal static string Constraint_LowerThan {
            get {
                return ResourceManager.GetString("Constraint_LowerThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinto a.
        /// </summary>
        internal static string Constraint_NotEqual {
            get {
                return ResourceManager.GetString("Constraint_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no posee permisos para ejecutar la acción que desea realizar..
        /// </summary>
        internal static string MethodAccessDeniedErrorMessage {
            get {
                return ResourceManager.GetString("MethodAccessDeniedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro especificado no existe..
        /// </summary>
        internal static string ObjectNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("ObjectNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Alertas.
        /// </summary>
        internal static string Securizable_AlertConfiguration {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días.
        /// </summary>
        internal static string Securizable_AlertConfiguration_Days {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultima Fecha de Envío.
        /// </summary>
        internal static string Securizable_AlertConfiguration_LastSentDate {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration_LastSentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máxima Cantidad de Días Pendiente de Aprobación.
        /// </summary>
        internal static string Securizable_AlertConfiguration_MaxDaysPendingAproval {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration_MaxDaysPendingAproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Email a Creador.
        /// </summary>
        internal static string Securizable_AlertConfiguration_SendEmailToCreator {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration_SendEmailToCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Email a Empleados.
        /// </summary>
        internal static string Securizable_AlertConfiguration_SendEmailToEmployees {
            get {
                return ResourceManager.GetString("Securizable_AlertConfiguration_SendEmailToEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entidades.
        /// </summary>
        internal static string Securizable_Assembly {
            get {
                return ResourceManager.GetString("Securizable_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string Securizable_CountryState {
            get {
                return ResourceManager.GetString("Securizable_CountryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidades.
        /// </summary>
        internal static string Securizable_CountryState_Districts {
            get {
                return ResourceManager.GetString("Securizable_CountryState_Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Corto.
        /// </summary>
        internal static string Securizable_CountryState_ShortName {
            get {
                return ResourceManager.GetString("Securizable_CountryState_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Securizable_Customer {
            get {
                return ResourceManager.GetString("Securizable_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string Securizable_Customer_Address {
            get {
                return ResourceManager.GetString("Securizable_Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string Securizable_Customer_Apartment {
            get {
                return ResourceManager.GetString("Securizable_Customer_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string Securizable_Customer_City {
            get {
                return ResourceManager.GetString("Securizable_Customer_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        internal static string Securizable_Customer_CUIT {
            get {
                return ResourceManager.GetString("Securizable_Customer_CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string Securizable_Customer_District {
            get {
                return ResourceManager.GetString("Securizable_Customer_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Securizable_Customer_Email {
            get {
                return ResourceManager.GetString("Securizable_Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso.
        /// </summary>
        internal static string Securizable_Customer_Floor {
            get {
                return ResourceManager.GetString("Securizable_Customer_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Completa.
        /// </summary>
        internal static string Securizable_Customer_FullAddress {
            get {
                return ResourceManager.GetString("Securizable_Customer_FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string Securizable_Customer_MobilePhone {
            get {
                return ResourceManager.GetString("Securizable_Customer_MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Securizable_Customer_Phone {
            get {
                return ResourceManager.GetString("Securizable_Customer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abono.
        /// </summary>
        internal static string Securizable_Customer_Subscription {
            get {
                return ResourceManager.GetString("Securizable_Customer_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string Securizable_Customer_ZipCode {
            get {
                return ResourceManager.GetString("Securizable_Customer_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        internal static string Securizable_District {
            get {
                return ResourceManager.GetString("Securizable_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string Securizable_District_CountryState {
            get {
                return ResourceManager.GetString("Securizable_District_CountryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string Securizable_District_ZipCode {
            get {
                return ResourceManager.GetString("Securizable_District_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleado.
        /// </summary>
        internal static string Securizable_Employee {
            get {
                return ResourceManager.GetString("Securizable_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string Securizable_Employee_Category {
            get {
                return ResourceManager.GetString("Securizable_Employee_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Securizable_Employee_Email {
            get {
                return ResourceManager.GetString("Securizable_Employee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono de Emergencia.
        /// </summary>
        internal static string Securizable_Employee_EmergencyPhone {
            get {
                return ResourceManager.GetString("Securizable_Employee_EmergencyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legajo.
        /// </summary>
        internal static string Securizable_Employee_FileNumber {
            get {
                return ResourceManager.GetString("Securizable_Employee_FileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Securizable_Employee_Firstname {
            get {
                return ResourceManager.GetString("Securizable_Employee_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre Completo.
        /// </summary>
        internal static string Securizable_Employee_Fullname {
            get {
                return ResourceManager.GetString("Securizable_Employee_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string Securizable_Employee_Lastname {
            get {
                return ResourceManager.GetString("Securizable_Employee_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string Securizable_Employee_Password {
            get {
                return ResourceManager.GetString("Securizable_Employee_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string Securizable_Employee_Phone {
            get {
                return ResourceManager.GetString("Securizable_Employee_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Securizable_Employee_Roles {
            get {
                return ResourceManager.GetString("Securizable_Employee_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Securizable_Employee_Tickets {
            get {
                return ResourceManager.GetString("Securizable_Employee_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        internal static string Securizable_Employee_Username {
            get {
                return ResourceManager.GetString("Securizable_Employee_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría de Empleado.
        /// </summary>
        internal static string Securizable_EmployeeCategory {
            get {
                return ResourceManager.GetString("Securizable_EmployeeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Securizable_PrimaryKeyWithNameAndDescriptionDomainObject_Description {
            get {
                return ResourceManager.GetString("Securizable_PrimaryKeyWithNameAndDescriptionDomainObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Securizable_PrimaryKeyWithNameDomainObject_Name {
            get {
                return ResourceManager.GetString("Securizable_PrimaryKeyWithNameDomainObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producto.
        /// </summary>
        internal static string Securizable_Product {
            get {
                return ResourceManager.GetString("Securizable_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string Securizable_Product_Name {
            get {
                return ResourceManager.GetString("Securizable_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre y Descripción.
        /// </summary>
        internal static string Securizable_Product_NameAndDescription {
            get {
                return ResourceManager.GetString("Securizable_Product_NameAndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string Securizable_Product_Providers {
            get {
                return ResourceManager.GetString("Securizable_Product_Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Securizable_Product_Tickets {
            get {
                return ResourceManager.GetString("Securizable_Product_Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calificación de Proveedor.
        /// </summary>
        internal static string Securizable_ProviderCalification {
            get {
                return ResourceManager.GetString("Securizable_ProviderCalification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Securizable_Ticket {
            get {
                return ResourceManager.GetString("Securizable_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presupuesto.
        /// </summary>
        internal static string Securizable_Ticket_Budget {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Creación.
        /// </summary>
        internal static string Securizable_Ticket_CreationDate {
            get {
                return ResourceManager.GetString("Securizable_Ticket_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creador.
        /// </summary>
        internal static string Securizable_Ticket_Creator {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string Securizable_Ticket_Customer {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Arrivo al Cliente.
        /// </summary>
        internal static string Securizable_Ticket_CustomerArrival {
            get {
                return ResourceManager.GetString("Securizable_Ticket_CustomerArrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string Securizable_Ticket_Description {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnicos Asignados.
        /// </summary>
        internal static string Securizable_Ticket_Employees {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Estimada.
        /// </summary>
        internal static string Securizable_Ticket_EstimatedDuration {
            get {
                return ResourceManager.GetString("Securizable_Ticket_EstimatedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Ejecución.
        /// </summary>
        internal static string Securizable_Ticket_ExecutionDate {
            get {
                return ResourceManager.GetString("Securizable_Ticket_ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string Securizable_Ticket_Products {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración Real.
        /// </summary>
        internal static string Securizable_Ticket_RealDuration {
            get {
                return ResourceManager.GetString("Securizable_Ticket_RealDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string Securizable_Ticket_Status {
            get {
                return ResourceManager.GetString("Securizable_Ticket_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Ticket.
        /// </summary>
        internal static string Securizable_TicketStatus {
            get {
                return ResourceManager.GetString("Securizable_TicketStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cantidad de días debe ser mayor o igual a 0.
        /// </summary>
        internal static string Validators_AlertConfiguration_Days {
            get {
                return ResourceManager.GetString("Validators_AlertConfiguration_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La máxima cantidad de días como pendiente de aprovación debe ser mayor o igual a 0.
        /// </summary>
        internal static string Validators_AlertConfiguration_MaxDaysPendingAproval {
            get {
                return ResourceManager.GetString("Validators_AlertConfiguration_MaxDaysPendingAproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dirección debe tener una longitud igual o menor a 50 caracteres..
        /// </summary>
        internal static string Validators_Customer_Address_Length {
            get {
                return ResourceManager.GetString("Validators_Customer_Address_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo CUIT debe tener el formato 00-00000000-0..
        /// </summary>
        internal static string Validators_Customer_CUIT {
            get {
                return ResourceManager.GetString("Validators_Customer_CUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \d{2}-\d{8}-\d{1}.
        /// </summary>
        internal static string Validators_Customer_CUIT_Pattern {
            get {
                return ResourceManager.GetString("Validators_Customer_CUIT_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail es inválido.
        /// </summary>
        internal static string Validators_Customer_Email {
            get {
                return ResourceManager.GetString("Validators_Customer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail es inválido.
        /// </summary>
        internal static string Validators_Employee_Email {
            get {
                return ResourceManager.GetString("Validators_Employee_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario es requerido.
        /// </summary>
        internal static string Validators_Employee_Username {
            get {
                return ResourceManager.GetString("Validators_Employee_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe tener una longitud entre 1 y 50 caracteres..
        /// </summary>
        internal static string Validators_PrimaryKeyDomainObject_Name_Length {
            get {
                return ResourceManager.GetString("Validators_PrimaryKeyDomainObject_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre es requerido..
        /// </summary>
        internal static string Validators_PrimaryKeyDomainObject_Name_Required {
            get {
                return ResourceManager.GetString("Validators_PrimaryKeyDomainObject_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción es requerida.
        /// </summary>
        internal static string Validators_Product_Description_Required {
            get {
                return ResourceManager.GetString("Validators_Product_Description_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código debe tener una longitud entre 1 y 50 caracteres..
        /// </summary>
        internal static string Validators_Product_Name_Length {
            get {
                return ResourceManager.GetString("Validators_Product_Name_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código es requerido..
        /// </summary>
        internal static string Validators_Product_Name_Required {
            get {
                return ResourceManager.GetString("Validators_Product_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del contácto es requerido.
        /// </summary>
        internal static string Validators_Provider_ContactName_Required {
            get {
                return ResourceManager.GetString("Validators_Provider_ContactName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El e-mail es inválido.
        /// </summary>
        internal static string Validators_Provider_Email {
            get {
                return ResourceManager.GetString("Validators_Provider_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono primario es requerido.
        /// </summary>
        internal static string Validators_Provider_PrimaryPhone_Required {
            get {
                return ResourceManager.GetString("Validators_Provider_PrimaryPhone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El teléfono secundario es requerido.
        /// </summary>
        internal static string Validators_Provider_SecondaryPhone_Required {
            get {
                return ResourceManager.GetString("Validators_Provider_SecondaryPhone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El website es inválido.
        /// </summary>
        internal static string Validators_Provider_Website {
            get {
                return ResourceManager.GetString("Validators_Provider_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción es requerida.
        /// </summary>
        internal static string Validators_Role_Description {
            get {
                return ResourceManager.GetString("Validators_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El creador es requerido.
        /// </summary>
        internal static string Validators_Ticket_Creator {
            get {
                return ResourceManager.GetString("Validators_Ticket_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente es requerido.
        /// </summary>
        internal static string Validators_Ticket_Customer {
            get {
                return ResourceManager.GetString("Validators_Ticket_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La descripción del trabajo a realizar es requerida.
        /// </summary>
        internal static string Validators_Ticket_Description {
            get {
                return ResourceManager.GetString("Validators_Ticket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado es requerido.
        /// </summary>
        internal static string Validators_Ticket_Status {
            get {
                return ResourceManager.GetString("Validators_Ticket_Status", resourceCulture);
            }
        }
    }
}
