//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebSite", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar {0} a {1} de {2} registros..
        /// </summary>
        internal static string Controls_Pager_ItemRangeShow {
            get {
                return ResourceManager.GetString("Controls_Pager_ItemRangeShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando {0} a {1} de {2} registros..
        /// </summary>
        internal static string Controls_Pager_ItemRangeShowing {
            get {
                return ResourceManager.GetString("Controls_Pager_ItemRangeShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando registros del {0} al {1} de un total de {2}..
        /// </summary>
        internal static string Controls_Pager_ItemsCount {
            get {
                return ResourceManager.GetString("Controls_Pager_ItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar siguientes {0} de {1} registros..
        /// </summary>
        internal static string Controls_Pager_NextItemRangeShow {
            get {
                return ResourceManager.GetString("Controls_Pager_NextItemRangeShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siguiente.
        /// </summary>
        internal static string Controls_Pager_NextLink {
            get {
                return ResourceManager.GetString("Controls_Pager_NextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página:.
        /// </summary>
        internal static string Controls_Pager_PageClause {
            get {
                return ResourceManager.GetString("Controls_Pager_PageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anterior.
        /// </summary>
        internal static string Controls_Pager_PreviousLink {
            get {
                return ResourceManager.GetString("Controls_Pager_PreviousLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        internal static string FilterPanelTitle {
            get {
                return ResourceManager.GetString("FilterPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/Default/Images/iconDelete.gif.
        /// </summary>
        internal static string IconDeleteImagePath {
            get {
                return ResourceManager.GetString("IconDeleteImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;App_Themes/Default/Images/iconEdit.gif&apos; /&gt;.
        /// </summary>
        internal static string IconEditImageTag {
            get {
                return ResourceManager.GetString("IconEditImageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/App_Themes/Default/Images/iconRecycle.gif.
        /// </summary>
        internal static string IconRecycleImagePath {
            get {
                return ResourceManager.GetString("IconRecycleImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&apos;App_Themes/Default/Images/iconView.gif&apos; /&gt;.
        /// </summary>
        internal static string IconViewImageTag {
            get {
                return ResourceManager.GetString("IconViewImageTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos marcados con * son requeridos.
        /// </summary>
        internal static string RequiredInformationText {
            get {
                return ResourceManager.GetString("RequiredInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
