//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagge.Seti.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bagge.Seti.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El CUIT ingresado ya existe..
        /// </summary>
        internal static string CUITNotUniqueErrorMessage {
            get {
                return ResourceManager.GetString("CUITNotUniqueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede elminar el cliente ya que esta asociado a un ticket no cerrado o no cancelado.
        /// </summary>
        internal static string CustomerTicketRelatedErrorMessage {
            get {
                return ResourceManager.GetString("CustomerTicketRelatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado cuyo e-mail es {0} no pudo ser encontrado.
        /// </summary>
        internal static string EmployeeByEmailNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("EmployeeByEmailNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El empleado cuyo nombre de usuario es {0} no pudo ser encontrado.
        /// </summary>
        internal static string EmployeeByUsernameNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("EmployeeByUsernameNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es requerida.
        /// </summary>
        internal static string EmployeePasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmployeePasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El link de generación de contraseña es inválido.
        /// </summary>
        internal static string EmployeeRecoverPasswordKeyNotMatch {
            get {
                return ResourceManager.GetString("EmployeeRecoverPasswordKeyNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede elminar el empleado ya que esta asociado a un ticket no cerrado o no cancelado.
        /// </summary>
        internal static string EmployeeTicketRelatedErrorMessage {
            get {
                return ResourceManager.GetString("EmployeeTicketRelatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El id no puede ser {0}.
        /// </summary>
        internal static string IdCannotBeDefault {
            get {
                return ResourceManager.GetString("IdCannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto de tipo {0} no puede ser nulo.
        /// </summary>
        internal static string InstanceCannotBeNull {
            get {
                return ResourceManager.GetString("InstanceCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto de tipo {1} no puede tener un id igual a {0}.
        /// </summary>
        internal static string InstanceIdCannotBeDefault {
            get {
                return ResourceManager.GetString("InstanceIdCannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El objeto de tipo {1} cuyo id es {0} no pudo ser encontrado.
        /// </summary>
        internal static string InstanceNotFound {
            get {
                return ResourceManager.GetString("InstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay multiples registros con el mismo nombre..
        /// </summary>
        internal static string MultipleNamesErrorMessage {
            get {
                return ResourceManager.GetString("MultipleNamesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay multiples empleados con el mismo nombre de usuario.
        /// </summary>
        internal static string MultipleUsernamesErrorMessage {
            get {
                return ResourceManager.GetString("MultipleUsernamesErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede elminar el producto ya que esta asociado a un ticket no cerrado o no cancelado.
        /// </summary>
        internal static string ProductTicketRelatedErrorMessage {
            get {
                return ResourceManager.GetString("ProductTicketRelatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede elminar el proveedor ya que esta asociado a un ticket no cerrado o no cancelado.
        /// </summary>
        internal static string ProviderTicketRelatedErrorMessage {
            get {
                return ResourceManager.GetString("ProviderTicketRelatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},\n\tSu nueva contraseña es {1}.
        /// </summary>
        internal static string RecoverPasswordEmailBodyNewPassword {
            get {
                return ResourceManager.GetString("RecoverPasswordEmailBodyNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},\n\tPara iniciar el proceso de recuperación de contraseña, por favor siga el siguiente link:\n\n{1}.
        /// </summary>
        internal static string RecoverPasswordEmailBodyRegenerate {
            get {
                return ResourceManager.GetString("RecoverPasswordEmailBodyRegenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETI - Recuperación de Contraseña.
        /// </summary>
        internal static string RecoverPasswordEmailSubject {
            get {
                return ResourceManager.GetString("RecoverPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Accesibilidad.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todas.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager_FindAll {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todas por Propiedades.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager_FindAllByProperties {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager_FindAllByProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todas por Propiedad.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager_FindAllByProperty {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager_FindAllByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todas por Tipo.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager_FindAllByType {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager_FindAllByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string Securizable_AccessibilityTypeManager_Get {
            get {
                return ResourceManager.GetString("Securizable_AccessibilityTypeManager_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Alertas.
        /// </summary>
        internal static string Securizable_AlertConfigurationManager {
            get {
                return ResourceManager.GetString("Securizable_AlertConfigurationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string Securizable_AlertConfigurationManager_Get {
            get {
                return ResourceManager.GetString("Securizable_AlertConfigurationManager_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Securizable_AlertConfigurationManager_Update {
            get {
                return ResourceManager.GetString("Securizable_AlertConfigurationManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lógica de Negocios.
        /// </summary>
        internal static string Securizable_Assembly {
            get {
                return ResourceManager.GetString("Securizable_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string Securizable_CustomerManager {
            get {
                return ResourceManager.GetString("Securizable_CustomerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por CUIT.
        /// </summary>
        internal static string Securizable_CustomerManager_GetByCuit {
            get {
                return ResourceManager.GetString("Securizable_CustomerManager_GetByCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string Securizable_EmployeeManager {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticar.
        /// </summary>
        internal static string Securizable_EmployeeManager_Authenticate {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos los Técnicos Activos.
        /// </summary>
        internal static string Securizable_EmployeeManager_FindAllActiveTechnicians {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_FindAllActiveTechnicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por Email.
        /// </summary>
        internal static string Securizable_EmployeeManager_GetByEmail {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_GetByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por Nombre de Usuario.
        /// </summary>
        internal static string Securizable_EmployeeManager_GetByUsername {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_GetByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Contraseña.
        /// </summary>
        internal static string Securizable_EmployeeManager_RecoverPassword {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerar Contraseña.
        /// </summary>
        internal static string Securizable_EmployeeManager_RegeneratePassword {
            get {
                return ResourceManager.GetString("Securizable_EmployeeManager_RegeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funciones.
        /// </summary>
        internal static string Securizable_FunctionManager {
            get {
                return ResourceManager.GetString("Securizable_FunctionManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener Assemblies a Securizar.
        /// </summary>
        internal static string Securizable_FunctionManager_GetSecuredAssemblies {
            get {
                return ResourceManager.GetString("Securizable_FunctionManager_GetSecuredAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener Propiedades y Metodos a Securizar.
        /// </summary>
        internal static string Securizable_FunctionManager_GetSecuredMembers {
            get {
                return ResourceManager.GetString("Securizable_FunctionManager_GetSecuredMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtener Tipos a Securizar.
        /// </summary>
        internal static string Securizable_FunctionManager_GetSecuredTypes {
            get {
                return ResourceManager.GetString("Securizable_FunctionManager_GetSecuredTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar Registros.
        /// </summary>
        internal static string Securizable_GenericManager_Count {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar Registros por Propiedades.
        /// </summary>
        internal static string Securizable_GenericManager_CountByProperties {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_CountByProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contar Registros por Propiedad.
        /// </summary>
        internal static string Securizable_GenericManager_CountByProperty {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_CountByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear.
        /// </summary>
        internal static string Securizable_GenericManager_Create {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar.
        /// </summary>
        internal static string Securizable_GenericManager_Delete {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos.
        /// </summary>
        internal static string Securizable_GenericManager_FindAll {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Propiedades.
        /// </summary>
        internal static string Securizable_GenericManager_FindAllByProperties {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_FindAllByProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Propiedad.
        /// </summary>
        internal static string Securizable_GenericManager_FindAllByProperty {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_FindAllByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string Securizable_GenericManager_Get {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos Paginado.
        /// </summary>
        internal static string Securizable_GenericManager_SlicedFindAll {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_SlicedFindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Propiedades Paginado.
        /// </summary>
        internal static string Securizable_GenericManager_SlicedFindAllByProperties {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_SlicedFindAllByProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Propiedad Paginado.
        /// </summary>
        internal static string Securizable_GenericManager_SlicedFindAllByProperty {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_SlicedFindAllByProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        internal static string Securizable_GenericManager_Update {
            get {
                return ResourceManager.GetString("Securizable_GenericManager_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string Securizable_ProductManager {
            get {
                return ResourceManager.GetString("Securizable_ProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por Nombre.
        /// </summary>
        internal static string Securizable_ProductManager_GetByName {
            get {
                return ResourceManager.GetString("Securizable_ProductManager_GetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string Securizable_ProviderManager {
            get {
                return ResourceManager.GetString("Securizable_ProviderManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por CUIT.
        /// </summary>
        internal static string Securizable_ProviderManager_GetByCuit {
            get {
                return ResourceManager.GetString("Securizable_ProviderManager_GetByCuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar por Nombre.
        /// </summary>
        internal static string Securizable_ProviderManager_GetByName {
            get {
                return ResourceManager.GetString("Securizable_ProviderManager_GetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        internal static string Securizable_ReportManager {
            get {
                return ResourceManager.GetString("Securizable_ReportManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string Securizable_ReportManager_GetReport {
            get {
                return ResourceManager.GetString("Securizable_ReportManager_GetReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Securizable_RoleManager {
            get {
                return ResourceManager.GetString("Securizable_RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Simple Generico (Provincias, Localidades, etc).
        /// </summary>
        internal static string Securizable_SimpleFindGetManager {
            get {
                return ResourceManager.GetString("Securizable_SimpleFindGetManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string Securizable_TicketManager {
            get {
                return ResourceManager.GetString("Securizable_TicketManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Producto.
        /// </summary>
        internal static string Securizable_TicketManager_FindAllByProduct {
            get {
                return ResourceManager.GetString("Securizable_TicketManager_FindAllByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Proveedor.
        /// </summary>
        internal static string Securizable_TicketManager_FindAllByProvider {
            get {
                return ResourceManager.GetString("Securizable_TicketManager_FindAllByProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos por Status.
        /// </summary>
        internal static string Securizable_TicketManager_FindAllByStatus {
            get {
                return ResourceManager.GetString("Securizable_TicketManager_FindAllByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de los Tickets.
        /// </summary>
        internal static string Securizable_TicketStatusManager {
            get {
                return ResourceManager.GetString("Securizable_TicketStatusManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Todos.
        /// </summary>
        internal static string Securizable_TicketStatusManager_FindAll {
            get {
                return ResourceManager.GetString("Securizable_TicketStatusManager_FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargar.
        /// </summary>
        internal static string Securizable_TicketStatusManager_Get {
            get {
                return ResourceManager.GetString("Securizable_TicketStatusManager_Get", resourceCulture);
            }
        }
    }
}
