//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagge.Seti.WebSite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bagge.Seti.WebSite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Alertas.
        /// </summary>
        internal static string Securizable_AlertConfigurationEditor {
            get {
                return ResourceManager.GetString("Securizable_AlertConfigurationEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interfaz de Usuario.
        /// </summary>
        internal static string Securizable_Assembly {
            get {
                return ResourceManager.GetString("Securizable_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Clientes.
        /// </summary>
        internal static string Securizable_CustomerEditor {
            get {
                return ResourceManager.GetString("Securizable_CustomerEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Clientes.
        /// </summary>
        internal static string Securizable_CustomerList {
            get {
                return ResourceManager.GetString("Securizable_CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Clientes por Abono.
        /// </summary>
        internal static string Securizable_CustomersBySubscription {
            get {
                return ResourceManager.GetString("Securizable_CustomersBySubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Clientes por Ticket.
        /// </summary>
        internal static string Securizable_CustomersByTicket {
            get {
                return ResourceManager.GetString("Securizable_CustomersByTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Clientes Pendientes de Pago.
        /// </summary>
        internal static string Securizable_CustomersWithPendingPayment {
            get {
                return ResourceManager.GetString("Securizable_CustomersWithPendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Securizable_Default {
            get {
                return ResourceManager.GetString("Securizable_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Empleados.
        /// </summary>
        internal static string Securizable_EmployeeEditor {
            get {
                return ResourceManager.GetString("Securizable_EmployeeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Empleados.
        /// </summary>
        internal static string Securizable_EmployeeList {
            get {
                return ResourceManager.GetString("Securizable_EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Funciones.
        /// </summary>
        internal static string Securizable_FunctionEditor {
            get {
                return ResourceManager.GetString("Securizable_FunctionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Productos.
        /// </summary>
        internal static string Securizable_ProductEditor {
            get {
                return ResourceManager.GetString("Securizable_ProductEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Productos.
        /// </summary>
        internal static string Securizable_ProductList {
            get {
                return ResourceManager.GetString("Securizable_ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Productos por Proveedor.
        /// </summary>
        internal static string Securizable_ProductsByProvider {
            get {
                return ResourceManager.GetString("Securizable_ProductsByProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Productos Consumidos.
        /// </summary>
        internal static string Securizable_ProductsConsumed {
            get {
                return ResourceManager.GetString("Securizable_ProductsConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Proveedores.
        /// </summary>
        internal static string Securizable_ProviderEditor {
            get {
                return ResourceManager.GetString("Securizable_ProviderEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Proveedores.
        /// </summary>
        internal static string Securizable_ProviderList {
            get {
                return ResourceManager.GetString("Securizable_ProviderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Roles.
        /// </summary>
        internal static string Securizable_RoleEditor {
            get {
                return ResourceManager.GetString("Securizable_RoleEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Roles.
        /// </summary>
        internal static string Securizable_RoleList {
            get {
                return ResourceManager.GetString("Securizable_RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Roles por Usuario.
        /// </summary>
        internal static string Securizable_RolesByUser {
            get {
                return ResourceManager.GetString("Securizable_RolesByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Técnicos por Ticket.
        /// </summary>
        internal static string Securizable_TechniciansByTicket {
            get {
                return ResourceManager.GetString("Securizable_TechniciansByTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor de Tickets.
        /// </summary>
        internal static string Securizable_TicketEditor {
            get {
                return ResourceManager.GetString("Securizable_TicketEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listado de Tickets.
        /// </summary>
        internal static string Securizable_TicketList {
            get {
                return ResourceManager.GetString("Securizable_TicketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no posee acceso a la función solicitada.
        /// </summary>
        internal static string UserHasNoAccessErrorMessage {
            get {
                return ResourceManager.GetString("UserHasNoAccessErrorMessage", resourceCulture);
            }
        }
    }
}
