//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Configuración de Alertas.
        /// </summary>
        internal static string AlertConfiguration_editTitle {
            get {
                return ResourceManager.GetString("AlertConfiguration.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alertas.
        /// </summary>
        internal static string AlertConfiguration_title {
            get {
                return ResourceManager.GetString("AlertConfiguration.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Configuración de Alertas.
        /// </summary>
        internal static string AlertConfiguration_viewTitle {
            get {
                return ResourceManager.GetString("AlertConfiguration.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Cliente.
        /// </summary>
        internal static string CustomerEditor_editTitle {
            get {
                return ResourceManager.GetString("CustomerEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Cliente.
        /// </summary>
        internal static string CustomerEditor_title {
            get {
                return ResourceManager.GetString("CustomerEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Cliente.
        /// </summary>
        internal static string CustomerEditor_viewTitle {
            get {
                return ResourceManager.GetString("CustomerEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string CustomerList_title {
            get {
                return ResourceManager.GetString("CustomerList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Default_title {
            get {
                return ResourceManager.GetString("Default.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Empleado.
        /// </summary>
        internal static string EmployeeEditor_editTitle {
            get {
                return ResourceManager.GetString("EmployeeEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Empleado.
        /// </summary>
        internal static string EmployeeEditor_title {
            get {
                return ResourceManager.GetString("EmployeeEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Empleado.
        /// </summary>
        internal static string EmployeeEditor_viewTitle {
            get {
                return ResourceManager.GetString("EmployeeEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados.
        /// </summary>
        internal static string EmployeeList_title {
            get {
                return ResourceManager.GetString("EmployeeList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Insumo.
        /// </summary>
        internal static string ProductEditor_editTitle {
            get {
                return ResourceManager.GetString("ProductEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Insumo.
        /// </summary>
        internal static string ProductEditor_title {
            get {
                return ResourceManager.GetString("ProductEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Insumo.
        /// </summary>
        internal static string ProductEditor_viewTitle {
            get {
                return ResourceManager.GetString("ProductEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumos.
        /// </summary>
        internal static string ProductList_title {
            get {
                return ResourceManager.GetString("ProductList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proveedor.
        /// </summary>
        internal static string ProviderEditor_editTitle {
            get {
                return ResourceManager.GetString("ProviderEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Proveedor.
        /// </summary>
        internal static string ProviderEditor_title {
            get {
                return ResourceManager.GetString("ProviderEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Proveedor.
        /// </summary>
        internal static string ProviderEditor_viewTitle {
            get {
                return ResourceManager.GetString("ProviderEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string ProviderList_title {
            get {
                return ResourceManager.GetString("ProviderList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes por Abono.
        /// </summary>
        internal static string ReportCustomersBySubscription_title {
            get {
                return ResourceManager.GetString("ReportCustomersBySubscription.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes por Ticket.
        /// </summary>
        internal static string ReportCustomersByTicket_title {
            get {
                return ResourceManager.GetString("ReportCustomersByTicket.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes Pendientes de Pago.
        /// </summary>
        internal static string ReportCustomersWithPendingPayment_title {
            get {
                return ResourceManager.GetString("ReportCustomersWithPendingPayment.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumos por Proveedor.
        /// </summary>
        internal static string ReportProductsByProvider_title {
            get {
                return ResourceManager.GetString("ReportProductsByProvider.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insumos Consumidos.
        /// </summary>
        internal static string ReportProductsConsumed_title {
            get {
                return ResourceManager.GetString("ReportProductsConsumed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles por Usuario.
        /// </summary>
        internal static string ReportRolesByUser_title {
            get {
                return ResourceManager.GetString("ReportRolesByUser.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        internal static string Reports_title {
            get {
                return ResourceManager.GetString("Reports.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Técnicos por Tickets.
        /// </summary>
        internal static string ReportTechniciansByTicket_title {
            get {
                return ResourceManager.GetString("ReportTechniciansByTicket.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets Cerrados.
        /// </summary>
        internal static string ReportTicketsClosed_title {
            get {
                return ResourceManager.GetString("ReportTicketsClosed.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Rol.
        /// </summary>
        internal static string RoleEditor_editTitle {
            get {
                return ResourceManager.GetString("RoleEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Rol.
        /// </summary>
        internal static string RoleEditor_title {
            get {
                return ResourceManager.GetString("RoleEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Rol.
        /// </summary>
        internal static string RoleEditor_viewTitle {
            get {
                return ResourceManager.GetString("RoleEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string RoleList_title {
            get {
                return ResourceManager.GetString("RoleList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        internal static string Security_title {
            get {
                return ResourceManager.GetString("Security.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Ticket.
        /// </summary>
        internal static string TicketEditor_editTitle {
            get {
                return ResourceManager.GetString("TicketEditor.editTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta Ticket.
        /// </summary>
        internal static string TicketEditor_title {
            get {
                return ResourceManager.GetString("TicketEditor.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Ticket.
        /// </summary>
        internal static string TicketEditor_viewTitle {
            get {
                return ResourceManager.GetString("TicketEditor.viewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        internal static string TicketList_title {
            get {
                return ResourceManager.GetString("TicketList.title", resourceCulture);
            }
        }
    }
}
